sudo: false
dist: trusty
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable
language: node_js
node_js:
  - '6.9'
cache: yarn

install: yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn add firebase-tools

script:
  - npm run ng lint
  - npm run coverage
  - npm run prod

after_script:
  - ./cc-test-reporter after-build

deploy:
  skip_cleanup: true
  provider: script
  script: ./node_modules/firebase-tools/bin/firebase deploy --token $FIREBASE_TOKEN --non-interactive
  on:
    branch: master
