sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

install: npm install

before_script:
  - npm install promise-polyfill --save-exact
  - npm install -g firebase-tools

script:
  - npm run ng lint
  - npm run ng build --prod

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN --non-interactive
  on:
    branch: master
